CREATE_DATABASE = True
CHECK_ALL_TEST_DATA = False
TRAIN_DATASET_PATH = r'NewDataset\train'
TEST_DATASET_PATH = r'NewDataset\test'
RECOGNATION_HARDNESS = 5
RECOGNATION_NEIGHBERS = 8

PERSON_NOT_FOUND = 'Person Not Found'